### ISSUE TITLE
supprimer les # dans les urls 

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligencePython#1]
Les urls http://*/*#* sont considérés comme des urls différentes alors qu'elles renvoient à la même page mais à des ancres différentes ce qui n'est pas pertinent.

Il faudrait supprimer ses ancres  avant la détection de redondance d'url

**Comment by neoxium** [comment]
Résolu dans c74ef0dc39ca4621b6ffe8b00c776bfdfad78f12
