### ISSUE TITLE
relevance bug

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligencePython#19]
j'ai ajouté le mot 'meta' dans le dictionnaire et il m'a compté tous les mots qui commence par meta... alors qu'il aurait du chercher uniquement " meta " avec les espaces car c'est ce mot uniquement que je voulais. La relevance est inutilisable.

**Comment by neoxium** [comment]
Fixed in d813473cbf0958f9eb5a10cc33c6d91add12fcb4
