### ISSUE TITLE
Variables exports

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligencePython#2]
page.csv
- id_url
- url
- id_domain
- title
- description
- keywords
- depth
[full]
- content
- html (réfléchir aux liens relatif média avec la balise base pour lisibilité locale)

pagegexf

- _idem_

+ liens
- Source
- Destination
- Type
- Weight
- sourcedomain_destdomain

Nodegexf (voir aussi #3 )
- id_domain
- base_url
- domaintitle
- desc_domain
- keywords
- nb_expression

+ liens

- _idem_

**Comment by neoxium** [comment]
Pris en charge pour partie dans 8569301921c36f91ceacc2158385a4db92ed32a3
