### ISSUE TITLE
interprétation des heuristiques

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligencePython#4]
Un fichier heuristics.txt pour les heuristiques type

(une idée comme ça ?)

facebook.com/ -> */ (le dernier "/")
twiter.com/ -> ./ (ce nombre exact de "/" après le nom de domaine)
linkedin.com/ -> ././ (ici 2nd "/" après le nom de domaine)
slideshare.net/ -> ./
instagram.com/ ->./
youtube.com/ -> media (ne le référence pas comme une expression mais comme un media d'une expression)
vimeo.com -> media
dailymotion.com -> media
pinterest.fr ->./
pinterest.com ->./

etc...

est une fonction "heuristic --land=LAND --path=PATH" pour forcer un recalcul d'heuristique en cas de modif en cours

**Comment by neoxium** [comment]
Pris en charge dans 8569301921c36f91ceacc2158385a4db92ed32a3
