### ISSUE TITLE
ajouter --http: dans la fonction crawl

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligencePython#5]
Parfois les pages ou les domaines ne sont pas accessible momentanément. Pouvoir relancer certaines pages et site par http

**Comment by alakel** [comment]
du coup ajouter http réponse dans le domain crawl

**Comment by neoxium** [comment]
Fixed in 93410608c5c4f7252b7ffc73e6193f413df0900a
